# Generated by Django 4.1.2 on 2022-10-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_passwords_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
